import {
  Category,
  Tag,
  MasterIngredient,
  CookerProfile,
  DeliveryPersonProfile,
  Product,
  Coupon,
  PlatformSettings,
  User,
} from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Cakes & Cupcakes',
    slug: 'cakes-and-cupcakes',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
    description: 'Freshly baked homemade celebration cakes, cupcakes, and tea cakes made with premium butter.',
    displayOrder: 1,
    isActive: true,
    subcategories: [
      { id: 'sub-1', categoryId: 'cat-1', name: 'Chocolate Cakes', slug: 'chocolate-cakes', isActive: true },
      { id: 'sub-2', categoryId: 'cat-1', name: 'Birthday & Custom Cakes', slug: 'birthday-cakes', isActive: true },
      { id: 'sub-3', categoryId: 'cat-1', name: 'Cheesecakes', slug: 'cheesecakes', isActive: true },
    ],
  },
  {
    id: 'cat-2',
    name: 'Artisan Breads & Sourdough',
    slug: 'artisan-breads',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    description: 'Naturally fermented wild yeast sourdough loaves, focaccias, and whole wheat baguettes.',
    displayOrder: 2,
    isActive: true,
    subcategories: [
      { id: 'sub-4', categoryId: 'cat-2', name: 'Sourdough Loaves', slug: 'sourdough-loaves', isActive: true },
      { id: 'sub-5', categoryId: 'cat-2', name: 'Garlic Focaccia', slug: 'garlic-focaccia', isActive: true },
    ],
  },
  {
    id: 'cat-3',
    name: 'Cookies & Brownies',
    slug: 'cookies-brownies',
    imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&auto=format&fit=crop&q=80',
    description: 'Fudgy melted chocolate brownies, crisp butter cookies, and healthy oats cookies.',
    displayOrder: 3,
    isActive: true,
    subcategories: [
      { id: 'sub-6', categoryId: 'cat-3', name: 'Fudge Brownies', slug: 'fudge-brownies', isActive: true },
      { id: 'sub-7', categoryId: 'cat-3', name: 'Oat & Nut Cookies', slug: 'oat-cookies', isActive: true },
    ],
  },
  {
    id: 'cat-4',
    name: 'Homestyle Meals & Curries',
    slug: 'homestyle-meals',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80',
    description: 'Fresh warm family recipes cooked in small batches with cold-pressed oils and pure spices.',
    displayOrder: 4,
    isActive: true,
    subcategories: [
      { id: 'sub-8', categoryId: 'cat-4', name: 'Biryanis & Pulao', slug: 'biryanis-pulao', isActive: true },
      { id: 'sub-9', categoryId: 'cat-4', name: 'Traditional Curries', slug: 'traditional-curries', isActive: true },
    ],
  },
  {
    id: 'cat-5',
    name: 'Healthy & High Protein',
    slug: 'healthy-choices',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    description: 'Macro-calculated meals, zero refined sugar bakes, and nutrient-dense power snacks.',
    displayOrder: 5,
    isActive: true,
    subcategories: [
      { id: 'sub-10', categoryId: 'cat-5', name: 'Keto & Low Carb', slug: 'keto-low-carb', isActive: true },
      { id: 'sub-11', categoryId: 'cat-5', name: 'High Protein Bowls', slug: 'high-protein-bowls', isActive: true },
    ],
  },
];

export const INITIAL_TAGS: Tag[] = [
  { id: 'tag-1', name: 'Eggless', slug: 'eggless', color: '#16a34a', isDietary: true },
  { id: 'tag-2', name: 'Vegetarian', slug: 'vegetarian', color: '#16a34a', isDietary: true },
  { id: 'tag-3', name: 'Vegan', slug: 'vegan', color: '#059669', isDietary: true },
  { id: 'tag-4', name: 'Gluten Free', slug: 'gluten-free', color: '#d97706', isDietary: true },
  { id: 'tag-5', name: 'Low Sugar', slug: 'low-sugar', color: '#0284c7', isDietary: false },
  { id: 'tag-6', name: 'No Added Sugar', slug: 'no-added-sugar', color: '#0284c7', isDietary: false },
  { id: 'tag-7', name: 'High Protein', slug: 'high-protein', color: '#7c3aed', isDietary: false },
  { id: 'tag-8', name: 'Healthy', slug: 'healthy', color: '#059669', isDietary: false },
  { id: 'tag-9', name: 'Chocolate', slug: 'chocolate', color: '#78350f', isDietary: false },
  { id: 'tag-10', name: 'Trending', slug: 'trending', color: '#e11d48', isDietary: false },
  { id: 'tag-11', name: 'Best Seller', slug: 'best-seller', color: '#ea580c', isDietary: false },
  { id: 'tag-12', name: 'Homemade', slug: 'homemade', color: '#d97706', isDietary: false },
  { id: 'tag-13', name: 'Birthday', slug: 'birthday', color: '#ec4899', isDietary: false },
];

export const MASTER_INGREDIENTS: MasterIngredient[] = [
  {
    id: 'ing-1',
    name: 'All-Purpose Flour (Maida)',
    standardUnit: 'g',
    caloriesPer100: 364,
    proteinPer100: 10.3,
    carbsPer100: 76.3,
    fatPer100: 1.0,
    saturatedFatPer100: 0.2,
    sugarPer100: 0.3,
    fiberPer100: 2.7,
    sodiumPer100: 2,
    allergens: ['Gluten', 'Wheat'],
  },
  {
    id: 'ing-2',
    name: 'Whole Wheat Flour (Atta)',
    standardUnit: 'g',
    caloriesPer100: 340,
    proteinPer100: 13.2,
    carbsPer100: 72.0,
    fatPer100: 2.5,
    saturatedFatPer100: 0.4,
    sugarPer100: 0.4,
    fiberPer100: 10.7,
    sodiumPer100: 5,
    allergens: ['Gluten', 'Wheat'],
  },
  {
    id: 'ing-3',
    name: 'Granulated Cane Sugar',
    standardUnit: 'g',
    caloriesPer100: 387,
    proteinPer100: 0.0,
    carbsPer100: 100.0,
    fatPer100: 0.0,
    saturatedFatPer100: 0.0,
    sugarPer100: 99.8,
    fiberPer100: 0.0,
    sodiumPer100: 1,
    allergens: [],
  },
  {
    id: 'ing-4',
    name: 'Pure Butter (Dairy)',
    standardUnit: 'g',
    caloriesPer100: 717,
    proteinPer100: 0.85,
    carbsPer100: 0.06,
    fatPer100: 81.1,
    saturatedFatPer100: 51.4,
    sugarPer100: 0.06,
    fiberPer100: 0.0,
    sodiumPer100: 643,
    allergens: ['Milk'],
  },
  {
    id: 'ing-5',
    name: 'Dark Cocoa Powder (Unsweetened)',
    standardUnit: 'g',
    caloriesPer100: 228,
    proteinPer100: 19.6,
    carbsPer100: 57.9,
    fatPer100: 13.7,
    saturatedFatPer100: 8.1,
    sugarPer100: 1.8,
    fiberPer100: 33.2,
    sodiumPer100: 21,
    allergens: [],
  },
  {
    id: 'ing-6',
    name: 'Whole Milk',
    standardUnit: 'ml',
    caloriesPer100: 61,
    proteinPer100: 3.2,
    carbsPer100: 4.8,
    fatPer100: 3.3,
    saturatedFatPer100: 1.9,
    sugarPer100: 5.1,
    fiberPer100: 0.0,
    sodiumPer100: 43,
    allergens: ['Milk'],
  },
  {
    id: 'ing-7',
    name: 'Farm Fresh Egg (Large)',
    standardUnit: 'piece',
    caloriesPer100: 143,
    proteinPer100: 12.6,
    carbsPer100: 0.7,
    fatPer100: 9.5,
    saturatedFatPer100: 3.1,
    sugarPer100: 0.4,
    fiberPer100: 0.0,
    sodiumPer100: 142,
    allergens: ['Egg'],
  },
  {
    id: 'ing-8',
    name: 'Dark Chocolate (70% Cocoa)',
    standardUnit: 'g',
    caloriesPer100: 598,
    proteinPer100: 7.8,
    carbsPer100: 45.9,
    fatPer100: 42.6,
    saturatedFatPer100: 24.5,
    sugarPer100: 24.0,
    fiberPer100: 10.9,
    sodiumPer100: 20,
    allergens: ['Soy', 'Milk'],
  },
  {
    id: 'ing-9',
    name: 'Rolled Oats',
    standardUnit: 'g',
    caloriesPer100: 389,
    proteinPer100: 16.9,
    carbsPer100: 66.3,
    fatPer100: 6.9,
    saturatedFatPer100: 1.2,
    sugarPer100: 0.9,
    fiberPer100: 10.6,
    sodiumPer100: 2,
    allergens: [],
  },
  {
    id: 'ing-10',
    name: 'Raw Almonds',
    standardUnit: 'g',
    caloriesPer100: 579,
    proteinPer100: 21.2,
    carbsPer100: 21.6,
    fatPer100: 49.9,
    saturatedFatPer100: 3.8,
    sugarPer100: 4.4,
    fiberPer100: 12.5,
    sodiumPer100: 1,
    allergens: ['Tree nuts'],
  },
  {
    id: 'ing-11',
    name: 'Organic Honey',
    standardUnit: 'g',
    caloriesPer100: 304,
    proteinPer100: 0.3,
    carbsPer100: 82.4,
    fatPer100: 0.0,
    saturatedFatPer100: 0.0,
    sugarPer100: 82.1,
    fiberPer100: 0.2,
    sodiumPer100: 4,
    allergens: [],
  },
  {
    id: 'ing-12',
    name: 'Fresh Paneer (Cottage Cheese)',
    standardUnit: 'g',
    caloriesPer100: 265,
    proteinPer100: 18.3,
    carbsPer100: 3.4,
    fatPer100: 20.8,
    saturatedFatPer100: 13.0,
    sugarPer100: 2.1,
    fiberPer100: 0.0,
    sodiumPer100: 22,
    allergens: ['Milk'],
  },
  {
    id: 'ing-13',
    name: 'Sourdough Culture & Spring Water',
    standardUnit: 'g',
    caloriesPer100: 130,
    proteinPer100: 4.5,
    carbsPer100: 26.0,
    fatPer100: 0.4,
    saturatedFatPer100: 0.1,
    sugarPer100: 0.2,
    fiberPer100: 1.5,
    sodiumPer100: 5,
    allergens: ['Gluten', 'Wheat'],
  },
  {
    id: 'ing-14',
    name: 'Extra Virgin Olive Oil',
    standardUnit: 'ml',
    caloriesPer100: 884,
    proteinPer100: 0.0,
    carbsPer100: 0.0,
    fatPer100: 100.0,
    saturatedFatPer100: 14.2,
    sugarPer100: 0.0,
    fiberPer100: 0.0,
    sodiumPer100: 2,
    allergens: [],
  },
  {
    id: 'ing-15',
    name: 'Basmati Rice',
    standardUnit: 'g',
    caloriesPer100: 356,
    proteinPer100: 7.1,
    carbsPer100: 78.0,
    fatPer100: 0.9,
    saturatedFatPer100: 0.2,
    sugarPer100: 0.1,
    fiberPer100: 1.3,
    sodiumPer100: 2,
    allergens: [],
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'Platform Administrator',
    email: 'admin@homefood.local',
    phone: '+91 9876543210',
    role: 'ADMIN',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-cook-1',
    name: 'Anas Rahiman',
    email: 'anas.bakery@homefood.local',
    phone: '+91 9988776655',
    role: 'COOKER',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=200&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-cook-2',
    name: 'Priya Sharma',
    email: 'priya.bakes@homefood.local',
    phone: '+91 9822334455',
    role: 'COOKER',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=200&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-cook-3',
    name: 'Chef Sarah Matthew',
    email: 'sarah.sourdough@homefood.local',
    phone: '+91 9123456780',
    role: 'COOKER',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-rider-1',
    name: 'Arjun Das',
    email: 'arjun.rider@homefood.local',
    phone: '+91 9776655443',
    role: 'RIDER',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-rider-2',
    name: 'Kiran Verma',
    email: 'kiran.rider@homefood.local',
    phone: '+91 9665544332',
    role: 'RIDER',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-cust-1',
    name: 'Amina Fathima',
    email: 'amina.customer@homefood.local',
    phone: '+91 9554433221',
    role: 'CUSTOMER',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_COOKER_PROFILES: CookerProfile[] = [
  {
    id: 'cook-prof-1',
    userId: 'usr-cook-1',
    storeName: "Anas Artisanal Home Bakery",
    bio: 'Crafting luxury European-style cakes and velvet brownies using Belgian dark chocolate and pure butter. No artificial preservatives.',
    logoUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=300&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?w=1200&auto=format&fit=crop&q=80',
    status: 'APPROVED',
    rating: 4.9,
    totalReviews: 84,
    totalOrders: 192,
    fssaiLicenseNumber: 'FSSAI-21423019000124',
    address: 'Baker Street Villa, Panampilly Nagar, Kochi, Kerala 682036',
    latitude: 9.9675,
    longitude: 76.2995,
    platformDeliveryEnabled: true,
    selfDeliveryEnabled: true,
    customerPickupEnabled: true,
    selfDeliveryRadiusKm: 6.0,
    platformDeliveryRadiusKm: 12.0,
    minimumOrderValue: 250,
    averagePrepTimeMinutes: 45,
    maxDailyCapacity: 15,
    isOpenToday: true,
    openingHours: '10:00 AM - 09:00 PM',
  },
  {
    id: 'cook-prof-2',
    userId: 'usr-cook-2',
    storeName: "NutriBake by Priya",
    bio: 'Specializing in guilt-free wholesome baking: jaggery cakes, almond flour low-sugar cookies, and eggless diabetic-friendly treats.',
    logoUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=300&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&auto=format&fit=crop&q=80',
    status: 'APPROVED',
    rating: 4.8,
    totalReviews: 52,
    totalOrders: 110,
    fssaiLicenseNumber: 'FSSAI-21423019000889',
    address: 'Green Meadows Apt, Edappally, Kochi, Kerala 682024',
    latitude: 10.0248,
    longitude: 76.3082,
    platformDeliveryEnabled: true,
    selfDeliveryEnabled: false,
    customerPickupEnabled: true,
    selfDeliveryRadiusKm: 4.0,
    platformDeliveryRadiusKm: 10.0,
    minimumOrderValue: 180,
    averagePrepTimeMinutes: 30,
    maxDailyCapacity: 20,
    isOpenToday: true,
    openingHours: '09:00 AM - 07:00 PM',
  },
  {
    id: 'cook-prof-3',
    userId: 'usr-cook-3',
    storeName: "Wild Yeast Sourdough & Hearth",
    bio: 'Authentic 36-hour cold fermented wild sourdough loaves, crispy artisanal focaccia with rosemary and Kalamata olives.',
    logoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&auto=format&fit=crop&q=80',
    status: 'APPROVED',
    rating: 4.9,
    totalReviews: 67,
    totalOrders: 145,
    fssaiLicenseNumber: 'FSSAI-21423019000452',
    address: 'Fort Hearth Studio, Fort Kochi, Kerala 682001',
    latitude: 9.9658,
    longitude: 76.2427,
    platformDeliveryEnabled: true,
    selfDeliveryEnabled: true,
    customerPickupEnabled: true,
    selfDeliveryRadiusKm: 8.0,
    platformDeliveryRadiusKm: 15.0,
    minimumOrderValue: 200,
    averagePrepTimeMinutes: 60,
    maxDailyCapacity: 12,
    isOpenToday: true,
    openingHours: '08:30 AM - 06:00 PM',
  },
];

export const INITIAL_RIDER_PROFILES: DeliveryPersonProfile[] = [
  {
    id: 'rider-prof-1',
    userId: 'usr-rider-1',
    vehicleType: 'EV',
    vehicleNumber: 'KL-07-CD-4102',
    currentLatitude: 9.9701,
    currentLongitude: 76.2981,
    status: 'ONLINE',
    isActive: true,
    deliveryRadiusKm: 8.0,
    rating: 4.9,
    totalDeliveries: 312,
    todayEarnings: 450,
    totalEarnings: 21800,
  },
  {
    id: 'rider-prof-2',
    userId: 'usr-rider-2',
    vehicleType: 'BIKE',
    vehicleNumber: 'KL-07-BQ-8819',
    currentLatitude: 10.0210,
    currentLongitude: 76.3105,
    status: 'ONLINE',
    isActive: true,
    deliveryRadiusKm: 10.0,
    rating: 4.8,
    totalDeliveries: 189,
    todayEarnings: 270,
    totalEarnings: 14200,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    cookerId: 'cook-prof-1',
    name: 'Belgian Dark Chocolate Truffle Cake (500g)',
    slug: 'belgian-dark-chocolate-truffle-cake',
    description: 'Decadent, velvety truffle cake made with 70% pure cocoa, organic cane sugar, and farm dairy butter. Perfectly balanced sweetness with deep cocoa notes.',
    categoryId: 'cat-1',
    subcategoryId: 'sub-1',
    tagIds: ['tag-9', 'tag-10', 'tag-11', 'tag-12', 'tag-13'],
    price: 650,
    imageUrls: [
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&auto=format&fit=crop&q=80',
    ],
    netWeightGrams: 500,
    servingSizeGrams: 100,
    servingsCount: 5,
    prepTimeMinutes: 45,
    maxWaitLimitMinutes: 45, // Cream cake wait limit
    isAvailable: true,
    stockCount: 8,
    dailyCapacity: 10,
    bookedToday: 2,
    supportsPreorder: true,
    status: 'APPROVED',
    ingredients: [
      { id: 'pi-1', ingredientId: 'ing-1', name: 'All-Purpose Flour (Maida)', quantity: 120, unit: 'g' },
      { id: 'pi-2', ingredientId: 'ing-8', name: 'Dark Chocolate (70% Cocoa)', quantity: 130, unit: 'g' },
      { id: 'pi-3', ingredientId: 'ing-4', name: 'Pure Butter (Dairy)', quantity: 80, unit: 'g' },
      { id: 'pi-4', ingredientId: 'ing-3', name: 'Granulated Cane Sugar', quantity: 90, unit: 'g' },
      { id: 'pi-5', ingredientId: 'ing-7', name: 'Farm Fresh Egg (Large)', quantity: 2, unit: 'pieces' },
      { id: 'pi-6', ingredientId: 'ing-6', name: 'Whole Milk', quantity: 60, unit: 'ml' },
    ],
    detectedAllergens: ['Gluten', 'Wheat', 'Milk', 'Egg', 'Soy'],
    nutrition: {
      total: {
        calories: 1980,
        protein: 34.5,
        carbs: 215.0,
        fat: 108.5,
        saturatedFat: 62.0,
        sugar: 128.0,
        fiber: 18.2,
        sodium: 480,
      },
      per100g: {
        calories: 396,
        protein: 6.9,
        carbs: 43.0,
        fat: 21.7,
        saturatedFat: 12.4,
        sugar: 25.6,
        fiber: 3.6,
        sodium: 96,
      },
      perServing: {
        calories: 396,
        protein: 6.9,
        carbs: 43.0,
        fat: 21.7,
        saturatedFat: 12.4,
        sugar: 25.6,
        fiber: 3.6,
        sodium: 96,
      },
      servingWeightGrams: 100,
      servingsPerPackage: 5,
    },
    aiAnalysis: {
      summary: 'Rich in antioxidants from premium 70% dark chocolate. High calorie and moderate-to-high sugar content suited for celebrations and energy-dense indulgences.',
      healthGrade: 'B',
      sugarLevel: 'Moderate',
      calorieDensity: 'High',
      keyBenefits: ['Rich flavonoids from authentic dark cocoa', 'Wholesome dairy fats without palm oil or margarine'],
      dietaryCautions: ['Contains dairy, eggs, and gluten allergens', 'Customers managing blood sugar should enjoy in controlled portions'],
      disclaimer: 'Nutrition information is an estimate calculated directly from verified raw ingredient database values.',
      suggestedAlternatives: 'Try NutriBake Oat & Almond Cookies for a lower-sugar daily alternative.',
    },
    rating: 4.9,
    reviewCount: 38,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    cookerId: 'cook-prof-2',
    name: 'Wholesome Low-Sugar Oat & Almond Cookies (Pack of 8)',
    slug: 'low-sugar-oat-almond-cookies',
    description: 'Crispy, nutty, fiber-rich artisan cookies sweetened naturally with organic raw honey and roasted California almonds. 100% refined sugar-free.',
    categoryId: 'cat-3',
    subcategoryId: 'sub-7',
    tagIds: ['tag-5', 'tag-7', 'tag-8', 'tag-1', 'tag-12'],
    price: 320,
    imageUrls: [
      'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=80',
    ],
    netWeightGrams: 280,
    servingSizeGrams: 35,
    servingsCount: 8,
    prepTimeMinutes: 25,
    maxWaitLimitMinutes: 240, // Cookies dry snack
    isAvailable: true,
    stockCount: 15,
    dailyCapacity: 20,
    bookedToday: 4,
    supportsPreorder: true,
    status: 'APPROVED',
    ingredients: [
      { id: 'pi-7', ingredientId: 'ing-9', name: 'Rolled Oats', quantity: 120, unit: 'g' },
      { id: 'pi-8', ingredientId: 'ing-10', name: 'Raw Almonds', quantity: 70, unit: 'g' },
      { id: 'pi-9', ingredientId: 'ing-11', name: 'Organic Honey', quantity: 50, unit: 'g' },
      { id: 'pi-10', ingredientId: 'ing-4', name: 'Pure Butter (Dairy)', quantity: 40, unit: 'g' },
    ],
    detectedAllergens: ['Tree nuts', 'Milk'],
    nutrition: {
      total: {
        calories: 1240,
        protein: 36.2,
        carbs: 135.0,
        fat: 62.4,
        saturatedFat: 21.0,
        sugar: 44.0,
        fiber: 21.5,
        sodium: 260,
      },
      per100g: {
        calories: 442,
        protein: 12.9,
        carbs: 48.2,
        fat: 22.2,
        saturatedFat: 7.5,
        sugar: 15.7,
        fiber: 7.6,
        sodium: 92,
      },
      perServing: {
        calories: 155,
        protein: 4.5,
        carbs: 16.9,
        fat: 7.8,
        saturatedFat: 2.6,
        sugar: 5.5,
        fiber: 2.7,
        sodium: 32,
      },
      servingWeightGrams: 35,
      servingsPerPackage: 8,
    },
    aiAnalysis: {
      summary: 'High dietary fiber and heart-healthy monounsaturated fats from almonds. Very low sugar impact with clean satiety for fitness and breakfast.',
      healthGrade: 'A',
      sugarLevel: 'Low',
      calorieDensity: 'Moderate',
      keyBenefits: ['7.6g prebiotic beta-glucan fiber per 100g', 'No white refined sugar or artificial syrups', 'Eggless & vegetarian friendly'],
      dietaryCautions: ['Contains Tree Nuts (Almonds) and Milk (Butter)'],
      disclaimer: 'Nutrition information is an estimate calculated directly from verified raw ingredient database values.',
    },
    rating: 4.8,
    reviewCount: 29,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    cookerId: 'cook-prof-3',
    name: '36-Hour Naturally Leavened Wild Sourdough Loaf (700g)',
    slug: 'wild-sourdough-loaf',
    description: 'Golden blistered crust with an airy, tender crumb. Slow fermented over 36 hours for easy digestion and complex hazelnut-sour notes. Just wild culture, water, unbleached flour, and sea salt.',
    categoryId: 'cat-2',
    subcategoryId: 'sub-4',
    tagIds: ['tag-3', 'tag-1', 'tag-2', 'tag-8', 'tag-12', 'tag-10'],
    price: 280,
    imageUrls: [
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
    ],
    netWeightGrams: 700,
    servingSizeGrams: 70,
    servingsCount: 10,
    prepTimeMinutes: 50,
    maxWaitLimitMinutes: 180,
    isAvailable: true,
    stockCount: 6,
    dailyCapacity: 12,
    bookedToday: 3,
    supportsPreorder: true,
    status: 'APPROVED',
    ingredients: [
      { id: 'pi-11', ingredientId: 'ing-2', name: 'Whole Wheat Flour (Atta)', quantity: 280, unit: 'g' },
      { id: 'pi-12', ingredientId: 'ing-1', name: 'All-Purpose Flour (Maida)', quantity: 220, unit: 'g' },
      { id: 'pi-13', ingredientId: 'ing-13', name: 'Sourdough Culture & Spring Water', quantity: 200, unit: 'g' },
      { id: 'pi-14', ingredientId: 'ing-14', name: 'Extra Virgin Olive Oil', quantity: 15, unit: 'ml' },
    ],
    detectedAllergens: ['Gluten', 'Wheat'],
    nutrition: {
      total: {
        calories: 1780,
        protein: 68.0,
        carbs: 350.0,
        fat: 22.0,
        saturatedFat: 3.2,
        sugar: 4.0,
        fiber: 36.0,
        sodium: 490,
      },
      per100g: {
        calories: 254,
        protein: 9.7,
        carbs: 50.0,
        fat: 3.1,
        saturatedFat: 0.4,
        sugar: 0.5,
        fiber: 5.1,
        sodium: 70,
      },
      perServing: {
        calories: 178,
        protein: 6.8,
        carbs: 35.0,
        fat: 2.2,
        saturatedFat: 0.3,
        sugar: 0.4,
        fiber: 3.6,
        sodium: 49,
      },
      servingWeightGrams: 70,
      servingsPerPackage: 10,
    },
    aiAnalysis: {
      summary: 'Remarkably clean macronutrient profile with near-zero sugar and high complex carbs. Long fermentation partially breaks down phytates and gluten proteins.',
      healthGrade: 'A',
      sugarLevel: 'Low',
      calorieDensity: 'Low',
      keyBenefits: ['100% Vegan with no dairy or eggs', 'Natural wild fermentation aids gut microbiome', 'Sustained energy release'],
      dietaryCautions: ['Contains gluten and wheat proteins'],
      disclaimer: 'Nutrition information is an estimate calculated directly from verified raw ingredient database values.',
    },
    rating: 4.9,
    reviewCount: 42,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    cookerId: 'cook-prof-1',
    name: 'Eggless Silk Chocolate Brownie Box (6 Pieces)',
    slug: 'eggless-silk-chocolate-brownie-box',
    description: 'Thick, crackly top, ultra-fudgy center. Made completely eggless with pure melted chocolate, unsalted farm butter, and Dutch cocoa.',
    categoryId: 'cat-3',
    subcategoryId: 'sub-6',
    tagIds: ['tag-1', 'tag-9', 'tag-11', 'tag-12'],
    price: 450,
    imageUrls: [
      'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=80',
    ],
    netWeightGrams: 420,
    servingSizeGrams: 70,
    servingsCount: 6,
    prepTimeMinutes: 35,
    maxWaitLimitMinutes: 120,
    isAvailable: true,
    stockCount: 10,
    dailyCapacity: 15,
    bookedToday: 5,
    supportsPreorder: true,
    status: 'APPROVED',
    ingredients: [
      { id: 'pi-15', ingredientId: 'ing-8', name: 'Dark Chocolate (70% Cocoa)', quantity: 150, unit: 'g' },
      { id: 'pi-16', ingredientId: 'ing-4', name: 'Pure Butter (Dairy)', quantity: 90, unit: 'g' },
      { id: 'pi-17', ingredientId: 'ing-1', name: 'All-Purpose Flour (Maida)', quantity: 90, unit: 'g' },
      { id: 'pi-18', ingredientId: 'ing-3', name: 'Granulated Cane Sugar', quantity: 90, unit: 'g' },
      { id: 'pi-19', ingredientId: 'ing-6', name: 'Whole Milk', quantity: 50, unit: 'ml' },
    ],
    detectedAllergens: ['Gluten', 'Wheat', 'Milk', 'Soy'],
    nutrition: {
      total: {
        calories: 1950,
        protein: 26.5,
        carbs: 210.0,
        fat: 112.0,
        saturatedFat: 68.0,
        sugar: 125.0,
        fiber: 19.5,
        sodium: 390,
      },
      per100g: {
        calories: 464,
        protein: 6.3,
        carbs: 50.0,
        fat: 26.6,
        saturatedFat: 16.1,
        sugar: 29.7,
        fiber: 4.6,
        sodium: 92,
      },
      perServing: {
        calories: 325,
        protein: 4.4,
        carbs: 35.0,
        fat: 18.6,
        saturatedFat: 11.3,
        sugar: 20.8,
        fiber: 3.2,
        sodium: 65,
      },
      servingWeightGrams: 70,
      servingsPerPackage: 6,
    },
    aiAnalysis: {
      summary: 'Decadent bakery treat with premium cocoa richness. Eggless formulation makes it suitable for vegetarian celebrations.',
      healthGrade: 'B',
      sugarLevel: 'Moderate',
      calorieDensity: 'High',
      keyBenefits: ['100% Eggless recipe', 'Rich pure butter texture without artificial shortening'],
      dietaryCautions: ['Contains dairy and gluten'],
      disclaimer: 'Nutrition information is an estimate calculated directly from verified raw ingredient database values.',
    },
    rating: 4.8,
    reviewCount: 22,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'WELCOME50',
    discountType: 'FIXED',
    discountValue: 50,
    minOrderValue: 250,
    validFrom: '2026-01-01',
    validUntil: '2027-12-31',
    usageLimit: 1000,
    timesUsed: 42,
    isActive: true,
    description: 'Flat ₹50 OFF on your first delicious homemade order (min ₹250)',
  },
  {
    id: 'coup-2',
    code: 'HOMEMADE10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 400,
    maxDiscountAmount: 100,
    validFrom: '2026-01-01',
    validUntil: '2027-12-31',
    usageLimit: 500,
    timesUsed: 19,
    isActive: true,
    description: '10% OFF up to ₹100 on artisanal orders above ₹400',
  },
];

export const DEFAULT_PLATFORM_SETTINGS: PlatformSettings = {
  commissionRatePercent: 10, // 10% platform commission
  baseDeliveryFee: 30, // ₹30 base delivery fee
  deliveryFeePerKm: 10, // ₹10 per km
  platformFee: 5, // ₹5 platform tech fee
  relevanceWeight: 40,
  distanceWeight: 20,
  ratingWeight: 15,
  availabilityWeight: 10,
  popularityWeight: 10,
  cookerQualityWeight: 5,
  otpExpiryMinutes: 5,
  otpCooldownSeconds: 60,
};
