import {
  Category,
  Tag,
  MasterIngredient,
  CookerProfile,
  DeliveryPersonProfile,
  Product,
  Coupon,
  PlatformSettings,
  User,
} from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Cakes & Cupcakes',
    slug: 'cakes-and-cupcakes',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
    description: 'Freshly baked homemade celebration cakes, cupcakes, and tea cakes made with premium butter.',
    displayOrder: 1,
    isActive: true,
    subcategories: [
      { id: 'sub-1', categoryId: 'cat-1', name: 'Chocolate Cakes', slug: 'chocolate-cakes', isActive: true },
      { id: 'sub-2', categoryId: 'cat-1', name: 'Birthday & Custom Cakes', slug: 'birthday-cakes', isActive: true },
      { id: 'sub-3', categoryId: 'cat-1', name: 'Cheesecakes', slug: 'cheesecakes', isActive: true },
    ],
  },
  {
    id: 'cat-2',
    name: 'Artisan Breads & Sourdough',
    slug: 'artisan-breads',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    description: 'Naturally fermented wild yeast sourdough loaves, focaccias, and whole wheat baguettes.',
    displayOrder: 2,
    isActive: true,
    subcategories: [
      { id: 'sub-4', categoryId: 'cat-2', name: 'Sourdough Loaves', slug: 'sourdough-loaves', isActive: true },
      { id: 'sub-5', categoryId: 'cat-2', name: 'Garlic Focaccia', slug: 'garlic-focaccia', isActive: true },
    ],
  },
  {
    id: 'cat-3',
    name: 'Cookies & Brownies',
    slug: 'cookies-brownies',
    imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&auto=format&fit=crop&q=80',
    description: 'Fudgy melted chocolate brownies, crisp butter cookies, and healthy oats cookies.',
    displayOrder: 3,
    isActive: true,
    subcategories: [
      { id: 'sub-6', categoryId: 'cat-3', name: 'Fudge Brownies', slug: 'fudge-brownies', isActive: true },
      { id: 'sub-7', categoryId: 'cat-3', name: 'Oat & Nut Cookies', slug: 'oat-cookies', isActive: true },
    ],
  },
  {
    id: 'cat-4',
    name: 'Homestyle Meals & Curries',
    slug: 'homestyle-meals',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80',
    description: 'Fresh warm family recipes cooked in small batches with cold-pressed oils and pure spices.',
    displayOrder: 4,
    isActive: true,
    subcategories: [
      { id: 'sub-8', categoryId: 'cat-4', name: 'Biryanis & Pulao', slug: 'biryanis-pulao', isActive: true },
      { id: 'sub-9', categoryId: 'cat-4', name: 'Traditional Curries', slug: 'traditional-curries', isActive: true },
    ],
  },
  {
    id: 'cat-5',
    name: 'Healthy & High Protein',
    slug: 'healthy-choices',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    description: 'Macro-calculated meals, zero refined sugar bakes, and nutrient-dense power snacks.',
    displayOrder: 5,
    isActive: true,
    subcategories: [
      { id: 'sub-10', categoryId: 'cat-5', name: 'Keto & Low Carb', slug: 'keto-low-carb', isActive: true },
      { id: 'sub-11', categoryId: 'cat-5', name: 'High Protein Bowls', slug: 'high-protein-bowls', isActive: true },
    ],
  },
];

export const INITIAL_TAGS: Tag[] = [
  { id: 'tag-1', name: 'Eggless', slug: 'eggless', color: '#16a34a', isDietary: true },
  { id: 'tag-2', name: 'Vegetarian', slug: 'vegetarian', color: '#16a34a', isDietary: true },
  { id: 'tag-3', name: 'Vegan', slug: 'vegan', color: '#059669', isDietary: true },
  { id: 'tag-4', name: 'Gluten Free', slug: 'gluten-free', color: '#d97706', isDietary: true },
  { id: 'tag-5', name: 'Low Sugar', slug: 'low-sugar', color: '#0284c7', isDietary: false },
  { id: 'tag-6', name: 'No Added Sugar', slug: 'no-added-sugar', color: '#0284c7', isDietary: false },
  { id: 'tag-7', name: 'High Protein', slug: 'high-protein', color: '#7c3aed', isDietary: false },
  { id: 'tag-8', name: 'Healthy', slug: 'healthy', color: '#059669', isDietary: false },
  { id: 'tag-9', name: 'Chocolate', slug: 'chocolate', color: '#78350f', isDietary: false },
  { id: 'tag-10', name: 'Trending', slug: 'trending', color: '#e11d48', isDietary: false },
  { id: 'tag-11', name: 'Best Seller', slug: 'best-seller', color: '#ea580c', isDietary: false },
  { id: 'tag-12', name: 'Homemade', slug: 'homemade', color: '#d97706', isDietary: false },
  { id: 'tag-13', name: 'Birthday', slug: 'birthday', color: '#ec4899', isDietary: false },
];

export const MASTER_INGREDIENTS: MasterIngredient[] = [
  {
    id: 'ing-1',
    name: 'All-Purpose Flour (Maida)',
    standardUnit: 'g',
    caloriesPer100: 364,
    proteinPer100: 10.3,
    carbsPer100: 76.3,
    fatPer100: 1.0,
    saturatedFatPer100: 0.2,
    sugarPer100: 0.3,
    fiberPer100: 2.7,
    sodiumPer100: 2,
    allergens: ['Gluten', 'Wheat'],
  },
  {
    id: 'ing-2',
    name: 'Whole Wheat Flour (Atta)',
    standardUnit: 'g',
    caloriesPer100: 340,
    proteinPer100: 13.2,
    carbsPer100: 72.0,
    fatPer100: 2.5,
    saturatedFatPer100: 0.4,
    sugarPer100: 0.4,
    fiberPer100: 10.7,
    sodiumPer100: 5,
    allergens: ['Gluten', 'Wheat'],
  },
  {
    id: 'ing-3',
    name: 'Granulated Cane Sugar',
    standardUnit: 'g',
    caloriesPer100: 387,
    proteinPer100: 0.0,
    carbsPer100: 100.0,
    fatPer100: 0.0,
    saturatedFatPer100: 0.0,
    sugarPer100: 99.8,
    fiberPer100: 0.0,
    sodiumPer100: 1,
    allergens: [],
  },
  {
    id: 'ing-4',
    name: 'Pure Butter (Dairy)',
    standardUnit: 'g',
    caloriesPer100: 717,
    proteinPer100: 0.85,
    carbsPer100: 0.06,
    fatPer100: 81.1,
    saturatedFatPer100: 51.4,
    sugarPer100: 0.06,
    fiberPer100: 0.0,
    sodiumPer100: 643,
    allergens: ['Milk'],
  },
  {
    id: 'ing-5',
    name: 'Dark Cocoa Powder (Unsweetened)',
    standardUnit: 'g',
    caloriesPer100: 228,
    proteinPer100: 19.6,
    carbsPer100: 57.9,
    fatPer100: 13.7,
    saturatedFatPer100: 8.1,
    sugarPer100: 1.8,
    fiberPer100: 33.2,
    sodiumPer100: 21,
    allergens: [],
  },
  {
    id: 'ing-6',
    name: 'Whole Milk',
    standardUnit: 'ml',
    caloriesPer100: 61,
    proteinPer100: 3.2,
    carbsPer100: 4.8,
    fatPer100: 3.3,
    saturatedFatPer100: 1.9,
    sugarPer100: 5.1,
    fiberPer100: 0.0,
    sodiumPer100: 43,
    allergens: ['Milk'],
  },
  {
    id: 'ing-7',
    name: 'Farm Fresh Egg (Large)',
    standardUnit: 'piece',
    caloriesPer100: 143,
    proteinPer100: 12.6,
    carbsPer100: 0.7,
    fatPer100: 9.5,
    saturatedFatPer100: 3.1,
    sugarPer100: 0.4,
    fiberPer100: 0.0,
    sodiumPer100: 142,
    allergens: ['Egg'],
  },
  {
    id: 'ing-8',
    name: 'Dark Chocolate (70% Cocoa)',
    standardUnit: 'g',
    caloriesPer100: 598,
    proteinPer100: 7.8,
    carbsPer100: 45.9,
    fatPer100: 42.6,
    saturatedFatPer100: 24.5,
    sugarPer100: 24.0,
    fiberPer100: 10.9,
    sodiumPer100: 20,
    allergens: ['Soy', 'Milk'],
  },
  {
    id: 'ing-9',
    name: 'Rolled Oats',
    standardUnit: 'g',
    caloriesPer100: 389,
    proteinPer100: 16.9,
    carbsPer100: 66.3,
    fatPer100: 6.9,
    saturatedFatPer100: 1.2,
    sugarPer100: 0.9,
    fiberPer100: 10.6,
    sodiumPer100: 2,
    allergens: [],
  },
  {
    id: 'ing-10',
    name: 'Raw Almonds',
    standardUnit: 'g',
    caloriesPer100: 579,
    proteinPer100: 21.2,
    carbsPer100: 21.6,
    fatPer100: 49.9,
    saturatedFatPer100: 3.8,
    sugarPer100: 4.4,
    fiberPer100: 12.5,
    sodiumPer100: 1,
    allergens: ['Tree nuts'],
  },
  {
    id: 'ing-11',
    name: 'Organic Honey',
    standardUnit: 'g',
    caloriesPer100: 304,
    proteinPer100: 0.3,
    carbsPer100: 82.4,
    fatPer100: 0.0,
    saturatedFatPer100: 0.0,
    sugarPer100: 82.1,
    fiberPer100: 0.2,
    sodiumPer100: 4,
    allergens: [],
  },
  {
    id: 'ing-12',
    name: 'Fresh Paneer (Cottage Cheese)',
    standardUnit: 'g',
    caloriesPer100: 265,
    proteinPer100: 18.3,
    carbsPer100: 3.4,
    fatPer100: 20.8,
    saturatedFatPer100: 13.0,
    sugarPer100: 2.1,
    fiberPer100: 0.0,
    sodiumPer100: 22,
    allergens: ['Milk'],
  },
  {
    id: 'ing-13',
    name: 'Sourdough Culture & Spring Water',
    standardUnit: 'g',
    caloriesPer100: 130,
    proteinPer100: 4.5,
    carbsPer100: 26.0,
    fatPer100: 0.4,
    saturatedFatPer100: 0.1,
    sugarPer100: 0.2,
    fiberPer100: 1.5,
    sodiumPer100: 5,
    allergens: ['Gluten', 'Wheat'],
  },
  {
    id: 'ing-14',
    name: 'Extra Virgin Olive Oil',
    standardUnit: 'ml',
    caloriesPer100: 884,
    proteinPer100: 0.0,
    carbsPer100: 0.0,
    fatPer100: 100.0,
    saturatedFatPer100: 14.2,
    sugarPer100: 0.0,
    fiberPer100: 0.0,
    sodiumPer100: 2,
    allergens: [],
  },
  {
    id: 'ing-15',
    name: 'Basmati Rice',
    standardUnit: 'g',
    caloriesPer100: 356,
    proteinPer100: 7.1,
    carbsPer100: 78.0,
    fatPer100: 0.9,
    saturatedFatPer100: 0.2,
    sugarPer100: 0.1,
    fiberPer100: 1.3,
    sodiumPer100: 2,
    allergens: [],
  },
];

// ONLY 1 Default Admin User (Silu, Password: 123)
export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'Silu (Platform Administrator)',
    email: 'silu@homefood.local',
    phone: '+91 9876543210',
    role: 'ADMIN',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Clean slate: 0 dummy cookers (Register via /auth/register?role=COOKER)
export const INITIAL_COOKER_PROFILES: CookerProfile[] = [];

// Clean slate: 0 dummy riders (Created exclusively by Admin on Admin Dashboard)
export const INITIAL_RIDER_PROFILES: DeliveryPersonProfile[] = [];

// Clean slate: 0 dummy products (Created by verified cookers)
export const INITIAL_PRODUCTS: Product[] = [];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'WELCOME50',
    discountType: 'FIXED',
    discountValue: 50,
    minOrderValue: 250,
    validFrom: '2026-01-01',
    validUntil: '2027-12-31',
    usageLimit: 1000,
    timesUsed: 0,
    isActive: true,
    description: 'Flat ₹50 OFF on your first delicious homemade order (min ₹250)',
  },
  {
    id: 'coup-2',
    code: 'HOMEMADE10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 400,
    maxDiscountAmount: 100,
    validFrom: '2026-01-01',
    validUntil: '2027-12-31',
    usageLimit: 500,
    timesUsed: 0,
    isActive: true,
    description: '10% OFF up to ₹100 on artisanal orders above ₹400',
  },
];

export const DEFAULT_PLATFORM_SETTINGS: PlatformSettings = {
  commissionRatePercent: 10,
  baseDeliveryFee: 30,
  deliveryFeePerKm: 10,
  platformFee: 5,
  relevanceWeight: 40,
  distanceWeight: 20,
  ratingWeight: 15,
  availabilityWeight: 10,
  popularityWeight: 10,
  cookerQualityWeight: 5,
  otpExpiryMinutes: 5,
  otpCooldownSeconds: 60,
};
